language: go

go:
  - 1.3
  - tip

env:
  - TRAVIS_BUILD_DIR=$GOPATH

install:
  - go get github.com/smartystreets/goconvey
  - go get github.com/smartystreets/assertions

notifications:
  slack: codetheorie:GPFuC9JhdITb4S5j2Xn3o7ug